services:
  db:
    image: postgres:17-alpine
    container_name: bitbit-database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_USER_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - spring-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge